desc: cloudsql-mysql
triggers:
- name: ""
  pattens:
  - '**/*.go'
  - '**/*.html'
  env:
    FIREBASE_SERVICE_FILE: "./firebase.json"
    GCP_PROJECT_ID: "staging-can-work"
    PORT: 5000
    DEFAULT_HOST: "https://staging-can-work.firebaseapp.com/"
  cmd: clear; go build && ./open-graph
  shell: true
  delay: 100ms
  stop_timeout: 500ms
  signal: KILL
  kill_signal: ""
watch_paths:
- .
watch_depth: 0