image: registry.gitlab.com/canyacoin/canyacore/devops/gcloud-golang-111:1.0

stages:
  - deploy

variables:
  GOPATH: /go
  APP_PATH: $GOPATH/src/gitlab.com/$CI_PROJECT_PATH

before_script:
  - echo "+ perfoming build on alpine '`cat /etc/alpine-release`' with '`go version`'" 
  - echo "+ relocating cloned sources to $APP_PATH to satisfy go's package tree structure"
  - mkdir -p `dirname $APP_PATH`
  - mv /builds/$CI_PROJECT_PATH $APP_PATH
  - mkdir -p /builds/$CI_PROJECT_PATH
  - export GOPATH=$GOPATH

deploy:staging:
  stage: deploy
  environment:
    name: staging
  script:
    - cd $APP_PATH
    - echo "Deploy to staging target GAE instance with project ID $GCP_PROJECT_ID"
    - echo $GCP_KEY > /tmp/$CI_PIPELINE_ID.json
    - echo -n "+ using GCP KEY for staging deployer " && cat /tmp/$CI_PIPELINE_ID.json
    - echo $FIREBASE_KEY > ./firebase.json
    - echo $DISPATCH_YAML_STAGING | base64 -d > ./dispatch.yaml
    - go get
    - go get github.com/stretchr/testify/assert
    - go test -v
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud --quiet app deploy dispatch.yaml
    - gcloud --quiet app deploy app.staging.yaml
    - curl --fail https://open-graph-dot-$GCP_PROJECT_ID.appspot.com/status
  only:
    - master
  allow_failure: false

deploy:production:
  stage: deploy
  environment:
    name: production
  script:
    - cd $APP_PATH
    - echo "Deploy to production target GAE instance with project ID $GCP_PROJECT_ID"
    - echo $GCP_KEY > /tmp/$CI_PIPELINE_ID.json
    - echo -n "+ using GCP KEY for production deployer " && cat /tmp/$CI_PIPELINE_ID.json
    - echo $FIREBASE_KEY > ./firebase.json
    - echo $DISPATCH_YAML | base64 -d > ./dispatch.yaml
    - go get
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud --quiet app deploy dispatch.yaml
    - gcloud --quiet app deploy app.production.yaml
    - curl --fail https://open-graph-dot-$GCP_PROJECT_ID.appspot.com/status
  only:
    - master
  when: manual
  allow_failure: false
